# -*- coding: utf-8 -*-
"""Tables de référence : libellés CPV à 4 chiffres et départements français."""

CPV4 = {
    "0312": "Produits de l'horticulture et de la floriculture",
    "0322": "Légumes, fruits et fruits à coque",
    "0345": "Produits de pépinière",
    "0900": "Produits pétroliers, combustibles et électricité",
    "0912": "Combustibles gazeux",
    "0913": "Pétrole et produits dérivés",
    "0930": "Chauffage, énergie solaire et nucléaire",
    "0931": "Électricité",
    "0933": "Énergie solaire",
    "1421": "Gravier, sable, pierre concassée et agrégats",
    "1500": "Produits alimentaires, boissons et tabac",
    "1511": "Viande",
    "1530": "Fruits, légumes et produits connexes",
    "1550": "Produits laitiers",
    "1580": "Produits alimentaires divers",
    "1581": "Pain, pâtisserie fraîche et viennoiserie",
    "1588": "Produits de nutrition spéciale",
    "1589": "Produits alimentaires et produits secs divers",
    "1616": "Matériel d'horticulture",
    "1631": "Tondeuses",
    "1810": "Vêtements professionnels et vêtements de travail",
    "1811": "Vêtements professionnels",
    "1814": "Accessoires de vêtements de travail",
    "2211": "Livres imprimés",
    "2411": "Gaz industriels",
    "2496": "Produits chimiques divers",
    "3012": "Photocopieurs et matériel d'impression",
    "3016": "Cartes magnétiques",
    "3019": "Matériel et fournitures de bureau divers",
    "3020": "Matériel et fournitures informatiques",
    "3021": "Machines de traitement des données (matériel)",
    "3023": "Matériel informatique",
    "3100": "Machines et appareils électriques",
    "3152": "Lampes et appareils d'éclairage",
    "3160": "Matériel et appareillage électrique",
    "3168": "Fournitures et accessoires électriques",
    "3232": "Matériel audiovisuel et de télévision",
    "3234": "Microphones et haut-parleurs",
    "3240": "Réseaux (matériel)",
    "3252": "Matériel et câbles de télécommunication",
    "3300": "Équipements médicaux, pharmaceutiques et d'hygiène",
    "3310": "Équipements médicaux",
    "3311": "Matériel d'imagerie médicale",
    "3313": "Instruments et appareils dentaires",
    "3314": "Consommables médicaux",
    "3316": "Matériel de bloc opératoire",
    "3318": "Assistance fonctionnelle et matériel d'aide",
    "3319": "Appareils et instruments médicaux divers",
    "3360": "Produits pharmaceutiques",
    "3362": "Médicaments (sang et organes hématopoïétiques)",
    "3365": "Médicaments anti-infectieux et vaccins",
    "3366": "Médicaments (système nerveux, organes sensoriels)",
    "3369": "Médicaments divers",
    "3410": "Véhicules à moteur",
    "3411": "Voitures particulières",
    "3413": "Véhicules de transport de marchandises",
    "3414": "Véhicules automobiles lourds",
    "3430": "Pièces et accessoires pour véhicules",
    "3435": "Pneumatiques",
    "3491": "Véhicules non motorisés",
    "3492": "Matériel de signalisation routière",
    "3494": "Équipement ferroviaire",
    "3499": "Matériel de contrôle, de sécurité et de signalisation",
    "3511": "Matériel de lutte contre l'incendie et de sauvetage",
    "3512": "Matériel et appareils de surveillance et de sécurité",
    "3740": "Articles et équipement de sport",
    "3741": "Équipement de sports de plein air",
    "3752": "Jouets",
    "3753": "Articles de jeux et de loisirs",
    "3800": "Équipements de laboratoire, d'optique et de précision",
    "3834": "Instruments de mesure",
    "3842": "Instruments de mesure (débit, niveau, pression)",
    "3843": "Appareils de détection et d'analyse",
    "3851": "Microscopes",
    "3910": "Mobilier",
    "3913": "Mobilier de bureau",
    "3914": "Mobilier domestique",
    "3915": "Mobilier et équipements divers",
    "3916": "Mobilier scolaire",
    "3922": "Équipement de cuisine et articles de maison",
    "3929": "Équipements et fournitures divers",
    "3931": "Équipement de restauration collective",
    "3951": "Articles ménagers en textile",
    "3971": "Appareils électroménagers",
    "3983": "Produits de nettoyage",
    "4111": "Eau potable",
    "4212": "Pompes et compresseurs",
    "4241": "Matériel de levage et de manutention",
    "4251": "Climatisation et réfrigération",
    "4296": "Systèmes de commande et de contrôle",
    "4332": "Équipement de chantier",
    "4411": "Matériaux de construction",
    "4414": "Produits liés aux matériaux de construction",
    "4416": "Conduites, tuyauteries et canalisations",
    "4421": "Structures et parties de structures",
    "4422": "Ouvrages de menuiserie pour le bâtiment",
    "4431": "Articles en fil métallique",
    "4442": "Articles utilisés dans la construction",
    "4451": "Outillage",
    "4461": "Citernes, réservoirs, radiateurs et chaudières",
    "4481": "Peintures",
    "4500": "Travaux de construction",
    "4510": "Travaux de préparation de chantier",
    "4511": "Démolition de bâtiments et terrassement",
    "4520": "Construction d'ouvrages, génie civil",
    "4521": "Construction de bâtiments",
    "4522": "Ouvrages d'art et de génie civil",
    "4523": "Voiries, réseaux, lignes électriques et de communication",
    "4524": "Construction d'ouvrages hydrauliques",
    "4525": "Travaux pour mines, usines et industrie pétrolière",
    "4526": "Couverture et travaux spécialisés divers",
    "4530": "Travaux d'installation dans les bâtiments",
    "4531": "Travaux d'équipement électrique",
    "4532": "Travaux d'isolation",
    "4533": "Travaux de plomberie et chauffage",
    "4534": "Clôtures, garde-corps et dispositifs de sécurité",
    "4540": "Travaux de finition de bâtiment",
    "4541": "Travaux de plâtrerie",
    "4542": "Travaux de menuiserie et de charpenterie",
    "4543": "Revêtement des sols et des murs",
    "4544": "Travaux de peinture et de vitrerie",
    "4545": "Autres travaux de finition de bâtiment",
    "4800": "Logiciels et systèmes d'information",
    "4890": "Logiciels et systèmes informatiques divers",
    "5000": "Services de réparation et d'entretien",
    "5010": "Réparation et entretien de véhicules",
    "5011": "Réparation et entretien de véhicules à moteur",
    "5023": "Réparation et entretien de routes et équipements",
    "5031": "Entretien et réparation de machines de bureau",
    "5032": "Réparation et entretien d'ordinateurs",
    "5041": "Réparation de matériel de mesure et de contrôle",
    "5042": "Réparation et entretien de matériel médical",
    "5051": "Réparation de pompes, vannes et robinets",
    "5053": "Réparation et entretien de machines",
    "5061": "Réparation et entretien de matériel de sécurité",
    "5070": "Entretien des installations de bâtiment",
    "5071": "Entretien des installations électriques et mécaniques",
    "5072": "Entretien du chauffage central",
    "5075": "Entretien d'ascenseurs",
    "5080": "Services de réparation et d'entretien divers",
    "5088": "Réparation et entretien de mobilier",
    "5524": "Services de centres et maisons de vacances",
    "5532": "Services de distribution de repas",
    "5551": "Services de cantine",
    "5552": "Services traiteur",
    "6000": "Services de transport",
    "6010": "Services de transport routier",
    "6011": "Transport routier public de voyageurs",
    "6013": "Transport routier spécialisé de passagers",
    "6014": "Transport non régulier de passagers",
    "6017": "Location de véhicules avec chauffeur",
    "6351": "Services d'agences de voyage",
    "6371": "Services annexes des transports terrestres",
    "6412": "Services de messagerie",
    "6420": "Services de télécommunications",
    "6421": "Téléphonie et transmission de données",
    "6600": "Services financiers et d'assurance",
    "6613": "Services bancaires et financiers",
    "6651": "Services d'assurance",
    "7100": "Architecture, ingénierie, construction, inspection",
    "7120": "Services d'architecture et services connexes",
    "7121": "Services de conseil en architecture",
    "7122": "Services de création architecturale",
    "7124": "Architecture, ingénierie et planification",
    "7125": "Architecture, ingénierie et métrage",
    "7130": "Services d'ingénierie",
    "7131": "Conseil en ingénierie et construction",
    "7132": "Services de conception technique",
    "7133": "Services divers d'ingénierie",
    "7135": "Services scientifiques et techniques en ingénierie",
    "7141": "Services d'urbanisme",
    "7152": "Conduite et surveillance de travaux",
    "7160": "Essais techniques, analyses et conseil",
    "7162": "Services d'analyse",
    "7163": "Contrôle et essais techniques",
    "7200": "Services informatiques (conseil, développement, internet)",
    "7221": "Programmation de progiciels",
    "7222": "Conseil en systèmes et conseil technique",
    "7224": "Analyse et programmation de systèmes",
    "7225": "Maintenance des systèmes et assistance",
    "7226": "Services relatifs aux logiciels",
    "7231": "Services de traitement de données",
    "7241": "Services de fournisseurs internet",
    "7250": "Services informatiques",
    "7260": "Assistance informatique et conseil",
    "7520": "Prestations de services pour la collectivité",
    "7523": "Services de justice",
    "7531": "Services de prestations sociales",
    "7720": "Services sylvicoles",
    "7721": "Services de débardage",
    "7731": "Réalisation et entretien d'espaces verts",
    "7734": "Élagage des arbres et taille des haies",
    "7910": "Services juridiques",
    "7911": "Conseil et représentation juridiques",
    "7921": "Services de comptabilité et d'audit",
    "7931": "Services d'études de marché et de sondages",
    "7934": "Services de publicité et de marketing",
    "7940": "Conseil en affaires et en gestion",
    "7941": "Services de conseil en affaires et en gestion",
    "7953": "Services de traduction",
    "7960": "Services de recrutement",
    "7962": "Mise à disposition de personnel",
    "7963": "Services de personnel",
    "7971": "Services de sécurité et de gardiennage",
    "7980": "Services d'impression et services connexes",
    "7981": "Services d'impression",
    "7982": "Services liés à l'impression",
    "7993": "Services de conception et de création",
    "7995": "Organisation d'expositions, foires et congrès",
    "7999": "Services aux entreprises divers",
    "8000": "Services d'enseignement et de formation",
    "8050": "Services de formation",
    "8051": "Services de formation spécialisée",
    "8053": "Services de formation professionnelle",
    "8514": "Services de santé divers",
    "8530": "Services d'action sociale et services connexes",
    "8531": "Services d'action sociale",
    "9000": "Assainissement, déchets, environnement",
    "9047": "Services de curage des égouts",
    "9048": "Services de gestion des égouts",
    "9050": "Services liés aux déchets et aux ordures",
    "9051": "Élimination et traitement des ordures",
    "9052": "Déchets dangereux, toxiques et médicaux",
    "9061": "Voirie et balayage des rues",
    "9062": "Services de déneigement",
    "9070": "Services relatifs à l'environnement",
    "9071": "Gestion environnementale",
    "9090": "Services de nettoyage et d'hygiénisation",
    "9091": "Services de nettoyage",
    "9092": "Désinfection et désinsectisation",
    "9200": "Services récréatifs, culturels et sportifs",
    "9211": "Production de films et de vidéos",
    "9230": "Services de divertissement",
    "9231": "Création et interprétation artistiques",
    "9233": "Services de zones récréatives",
    "9251": "Services de bibliothèques et d'archives",
    "9252": "Services de musées et de sites historiques",
    "9262": "Services liés au sport",
    "9831": "Blanchisserie et nettoyage à sec",
    "9839": "Autres services divers",
}

DEPARTEMENTS = {
    "01": "Ain", "02": "Aisne", "03": "Allier", "04": "Alpes-de-Haute-Provence",
    "05": "Hautes-Alpes", "06": "Alpes-Maritimes", "07": "Ardèche", "08": "Ardennes",
    "09": "Ariège", "10": "Aube", "11": "Aude", "12": "Aveyron",
    "13": "Bouches-du-Rhône", "14": "Calvados", "15": "Cantal", "16": "Charente",
    "17": "Charente-Maritime", "18": "Cher", "19": "Corrèze", "20": "Corse",
    "2A": "Corse-du-Sud", "2B": "Haute-Corse", "21": "Côte-d'Or",
    "22": "Côtes-d'Armor", "23": "Creuse", "24": "Dordogne", "25": "Doubs",
    "26": "Drôme", "27": "Eure", "28": "Eure-et-Loir", "29": "Finistère",
    "30": "Gard", "31": "Haute-Garonne", "32": "Gers", "33": "Gironde",
    "34": "Hérault", "35": "Ille-et-Vilaine", "36": "Indre", "37": "Indre-et-Loire",
    "38": "Isère", "39": "Jura", "40": "Landes", "41": "Loir-et-Cher",
    "42": "Loire", "43": "Haute-Loire", "44": "Loire-Atlantique", "45": "Loiret",
    "46": "Lot", "47": "Lot-et-Garonne", "48": "Lozère", "49": "Maine-et-Loire",
    "50": "Manche", "51": "Marne", "52": "Haute-Marne", "53": "Mayenne",
    "54": "Meurthe-et-Moselle", "55": "Meuse", "56": "Morbihan", "57": "Moselle",
    "58": "Nièvre", "59": "Nord", "60": "Oise", "61": "Orne", "62": "Pas-de-Calais",
    "63": "Puy-de-Dôme", "64": "Pyrénées-Atlantiques", "65": "Hautes-Pyrénées",
    "66": "Pyrénées-Orientales", "67": "Bas-Rhin", "68": "Haut-Rhin", "69": "Rhône",
    "70": "Haute-Saône", "71": "Saône-et-Loire", "72": "Sarthe", "73": "Savoie",
    "74": "Haute-Savoie", "75": "Paris", "76": "Seine-Maritime",
    "77": "Seine-et-Marne", "78": "Yvelines", "79": "Deux-Sèvres", "80": "Somme",
    "81": "Tarn", "82": "Tarn-et-Garonne", "83": "Var", "84": "Vaucluse",
    "85": "Vendée", "86": "Vienne", "87": "Haute-Vienne", "88": "Vosges",
    "89": "Yonne", "90": "Territoire de Belfort", "91": "Essonne",
    "92": "Hauts-de-Seine", "93": "Seine-Saint-Denis", "94": "Val-de-Marne",
    "95": "Val-d'Oise", "971": "Guadeloupe", "972": "Martinique", "973": "Guyane",
    "974": "La Réunion", "975": "Saint-Pierre-et-Miquelon", "976": "Mayotte",
    "977": "Saint-Barthélemy", "978": "Saint-Martin", "984": "TAAF",
    "986": "Wallis-et-Futuna", "987": "Polynésie française",
    "988": "Nouvelle-Calédonie",
}


def cpv4_label(code8):
    c = str(code8 or "").strip()
    c4 = c[:4]
    return c4, CPV4.get(c4, f"CPV {c4}" if c4 else "Non précisé")


def departement_from_lieu(code, type_code):
    if not code:
        return None
    c = str(code).strip().upper()
    tc = (type_code or "").lower()
    if "pays" in tc:
        return None
    if "département" in tc or "departement" in tc:
        c = c.zfill(2) if c.isdigit() and len(c) <= 2 else c
        return c if c in DEPARTEMENTS else None
    if "région" in tc or "region" in tc:
        return None
    if c[:2] in ("2A", "2B"):
        return c[:2]
    if c[:3] in ("971", "972", "973", "974", "975", "976", "977", "978",
                 "984", "986", "987", "988"):
        return c[:3]
    pref = c[:2]
    if pref.isdigit() and pref in DEPARTEMENTS:
        return pref
    return None
